const Sequelize=require('sequelize');

class HouseDraw extends Sequelize.Model{
    static initiate(sequelize){
        HouseDraw.init({
            house_id:{
                type: Sequelize.INTEGER,
                allowNull:true,
                unique:true,
                autoIncrement:true
            },
            house_image:{
                type:Sequelize.STRING(255),
                allowNull:true,
                unique:true
            },
            house:{
                type:Sequelize.INTEGER,
                allowNull:true,
            },
            house_size:{
                type:Sequelize.INTEGER,
                allowNull:true,
            },
            house_loc:{
                type:Sequelize.INTEGER,
                allowNull:true,
            },
            house_roof:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            house_wall:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            house_door:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            house_window:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            house_chimney:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            house_smoke:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            house_fence:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            house_road:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            house_pond:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            house_mountain:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            house_tree:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            house_flower:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            house_grass:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            house_sun:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
        },{
            sequelize,
            timestamps:true,
            underscored:false,
            modelName:'HouseDraw',
            tableName:'Housedraw',
            charset:'utf8',
            collate:'utf8_general_ci',
        });
    }
    static associate(db){
        db.HouseDraw.belongsTo(db.User,{foreignKey:'user_id',targetKey:'user_id'})
    }
};

module.exports=HouseDraw;
