const Sequelize=require('sequelize');

class PeopleDraw extends Sequelize.Model{
    static initiate(sequelize){
        PeopleDraw.init({
            people_id:{
                type: Sequelize.INTEGER,
                allowNull:true,
                unique:true,
                autoIncrement:true
            },
            people_image:{
                type:Sequelize.STRING(255),
                allowNull:true,
                unique:true
            },
            sex:{
                type:Sequelize.ENUM('Male','Female'),
                allowNull:true,
            },
            people:{
                type:Sequelize.INTEGER,
                allowNull:true,
            },
            people_size:{
                type:Sequelize.INTEGER,
                allowNull:true,
            },
            people_head:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_face:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_eye:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_nose:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_mouse:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_ear:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_hair:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_neck:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_body:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_arm:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_hand:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_leg:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_foot:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_button:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_pocket:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_runshoes:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
            people_shoes:{
                type:Sequelize.INTEGER,
                allowNull:true,
                defaultValue:0
            },
        },{
            sequelize,
            timestamps:true,
            underscored:false,
            modelName:'PeopleDraw',
            tableName:'peopledraw',
            charset:'utf8',
            collate:'utf8_general_ci',
        });
    }
    static associate(db){
        db.PeopleDraw.belongsTo(db.User,{foreignKey:'user_id',targetKey:'user_id'})
    }
};

module.exports=PeopleDraw;
